bda/urls.py
# -*- coding: utf-8 -*-

from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals

from django.conf.urls import url
from gestioncof.decorators import buro_required
from bda.views import SpectacleListView
from bda import views

urlpatterns = [
    url(r'^inscription/(?P<tirage_id>\d+)$',
        views.inscription,
        name='bda-tirage-inscription'),
    url(r'^places/(?P<tirage_id>\d+)$',
        views.places,
        name="bda-places-attribuees"),
    url(r'^revente/(?P<tirage_id>\d+)$',
        views.revente,
        name='bda-revente'),
    url(r'^etat-places/(?P<tirage_id>\d+)$',
        views.etat_places,
        name='bda-etat-places'),
    url(r'^tirage/(?P<tirage_id>\d+)$', views.tirage),
    url(r'^spectacles/(?P<tirage_id>\d+)$',
        buro_required(SpectacleListView.as_view()),
        name="bda-liste-spectacles"),
    url(r'^spectacles/(?P<tirage_id>\d+)/(?P<spectacle_id>\d+)$',
        views.spectacle,
        name="bda-spectacle"),
    url(r'^spectacles/unpaid/(?P<tirage_id>\d+)$',
        views.unpaid,
        name="bda-unpaid"),
    url(r'^liste-revente/(?P<tirage_id>\d+)$',
        views.list_revente,
        name="bda-liste-revente"),
    url(r'^buy-revente/(?P<spectacle_id>\d+)$',
        views.buy_revente,
        name="bda-buy-revente"),
    url(r'^revente-interested/(?P<revente_id>\d+)$',
        views.revente_interested,
        name='bda-revente-interested'),
    url(r'^revente-immediat/(?P<tirage_id>\d+)$',
        views.revente_shotgun,
        name="bda-shotgun"),
    url(r'^mails-rappel/(?P<spectacle_id>\d+)$',
        views.send_rappel,
        name="bda-rappels"
        ),
    url(r'^descriptions/(?P<tirage_id>\d+)$', views.descriptions_spectacles,
        name='bda-descriptions'),
    url(r'^catalogue/(?P<request_type>[a-z]+)$', views.catalogue,
        name='bda-catalogue'),
]

bda/models.py
# -*- coding: utf-8 -*-

import calendar
import random
from datetime import timedelta
from custommail.shortcuts import send_mass_custom_mail

from django.contrib.sites.models import Site
from django.db import models
from django.db.models import Count
from django.contrib.auth.models import User
from django.conf import settings
from django.utils import timezone, formats


def get_generic_user():
    generic, _ = User.objects.get_or_create(
        username="bda_generic",
        defaults={"email": "bda@ens.fr", "first_name": "Bureau des arts"}
    )
    return generic


class Tirage(models.Model):
    title = models.CharField("Titre", max_length=300)
    ouverture = models.DateTimeField("Date et heure d'ouverture du tirage")
    fermeture = models.DateTimeField("Date et heure de fermerture du tirage")
    tokens = models.TextField("Graine(s) du tirage", blank=True)
    active = models.BooleanField("Tirage actif", default=False)
    appear_catalogue = models.BooleanField(
        "Tirage à afficher dans le catalogue",
        default=False
    )
    enable_do_tirage = models.BooleanField("Le tirage peut être lancé",
                                           default=False)

    def __str__(self):
        return "%s - %s" % (self.title, formats.localize(
            timezone.template_localtime(self.fermeture)))


class Salle(models.Model):
    name = models.CharField("Nom", max_length=300)
    address = models.TextField("Adresse")

    def __str__(self):
        return self.name


class CategorieSpectacle(models.Model):
    name = models.CharField('Nom', max_length=100, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Catégorie"


class Spectacle(models.Model):
    title = models.CharField("Titre", max_length=300)
    category = models.ForeignKey(CategorieSpectacle, blank=True, null=True)
    date = models.DateTimeField("Date & heure")
    location = models.ForeignKey(Salle)
    vips = models.TextField('Personnalités', blank=True)
    description = models.TextField("Description", blank=True)
    slots_description = models.TextField("Description des places", blank=True)
    image = models.ImageField('Image', blank=True, null=True,
                              upload_to='imgs/shows/')
    ext_link = models.CharField('Lien vers le site du spectacle', blank=True,
                                max_length=500)
    price = models.FloatField("Prix d'une place")
    slots = models.IntegerField("Places")
    tirage = models.ForeignKey(Tirage)
    listing = models.BooleanField("Les places sont sur listing")
    rappel_sent = models.DateTimeField("Mail de rappel envoyé", blank=True,
                                       null=True)

    class Meta:
        verbose_name = "Spectacle"
        ordering = ("date", "title",)

    def timestamp(self):
        return "%d" % calendar.timegm(self.date.utctimetuple())

    def __str__(self):
        return "%s - %s, %s, %.02f€" % (
            self.title,
            formats.localize(timezone.template_localtime(self.date)),
            self.location,
            self.price
        )

    def getImgUrl(self):
        """
        Cette fonction permet d'obtenir l'URL de l'image, si elle existe
        """
        try:
            return self.image.url
        except:
            return None

    def send_rappel(self):
        """
        Envoie un mail de rappel à toutes les personnes qui ont une place pour
        ce spectacle.
        """
        # On récupère la liste des participants + le BdA
        members = list(
            User.objects
            .filter(participant__attributions=self)
            .annotate(nb_attr=Count("id")).order_by()
        )
        bda_generic = get_generic_user()
        bda_generic.nb_attr = 1
        members.append(bda_generic)
        # On écrit un mail personnalisé à chaque participant
        datatuple = [(
            'bda-rappel',
            {'member': member, "nb_attr": member.nb_attr, 'show': self},
            settings.MAIL_DATA['rappels']['FROM'],
            [member.email])
            for member in members
        ]
        send_mass_custom_mail(datatuple)
        # On enregistre le fait que l'envoi a bien eu lieu
        self.rappel_sent = timezone.now()
        self.save()
        # On renvoie la liste des destinataires
        return members

    @property
    def is_past(self):
        return self.date < timezone.now()


class Quote(models.Model):
    spectacle = models.ForeignKey(Spectacle)
    text = models.TextField('Citation')
    author = models.CharField('Auteur', max_length=200)


PAYMENT_TYPES = (
    ("cash", "Cash"),
    ("cb", "CB"),
    ("cheque", "Chèque"),
    ("autre", "Autre"),
)


class Participant(models.Model):
    user = models.ForeignKey(User)
    choices = models.ManyToManyField(Spectacle,
                                     through="ChoixSpectacle",
                                     related_name="chosen_by")
    attributions = models.ManyToManyField(Spectacle,
                                          through="Attribution",
                                          related_name="attributed_to")
    paid = models.BooleanField("A payé", default=False)
    paymenttype = models.CharField("Moyen de paiement",
                                   max_length=6, choices=PAYMENT_TYPES,
                                   blank=True)
    tirage = models.ForeignKey(Tirage)
    choicesrevente = models.ManyToManyField(Spectacle,
                                            related_name="subscribed",
                                            blank=True)

    def __str__(self):
        return "%s - %s" % (self.user, self.tirage.title)

DOUBLE_CHOICES = (
    ("1", "1 place"),
    ("autoquit", "2 places si possible, 1 sinon"),
    ("double", "2 places sinon rien"),
)


class ChoixSpectacle(models.Model):
    participant = models.ForeignKey(Participant)
    spectacle = models.ForeignKey(Spectacle, related_name="participants")
    priority = models.PositiveIntegerField("Priorité")
    double_choice = models.CharField("Nombre de places",
                                     default="1", choices=DOUBLE_CHOICES,
                                     max_length=10)

    def get_double(self):
        return self.double_choice != "1"
    double = property(get_double)

    def get_autoquit(self):
        return self.double_choice == "autoquit"
    autoquit = property(get_autoquit)

    def __str__(self):
        return "Vœux de %s pour %s" % (
                self.participant.user.get_full_name(),
                self.spectacle.title)

    class Meta:
        ordering = ("priority",)
        unique_together = (("participant", "spectacle",),)
        verbose_name = "voeu"
        verbose_name_plural = "voeux"


class Attribution(models.Model):
    participant = models.ForeignKey(Participant)
    spectacle = models.ForeignKey(Spectacle, related_name="attribues")
    given = models.BooleanField("Donnée", default=False)

    def __str__(self):
        return "%s -- %s, %s" % (self.participant.user, self.spectacle.title,
                                 self.spectacle.date)


class SpectacleRevente(models.Model):
    attribution = models.OneToOneField(Attribution,
                                       related_name="revente")
    date = models.DateTimeField("Date de mise en vente",
                                default=timezone.now)
    answered_mail = models.ManyToManyField(Participant,
                                           related_name="wanted",
                                           blank=True)
    seller = models.ForeignKey(Participant,
                               related_name="original_shows",
                               verbose_name="Vendeur")
    soldTo = models.ForeignKey(Participant, blank=True, null=True,
                               verbose_name="Vendue à")

    notif_sent = models.BooleanField("Notification envoyée",
                                     default=False)
    tirage_done = models.BooleanField("Tirage effectué",
                                      default=False)
    shotgun = models.BooleanField("Disponible immédiatement",
                                  default=False)

    @property
    def date_tirage(self):
        """Renvoie la date du tirage au sort de la revente."""
        # L'acheteur doit être connu au plus 12h avant le spectacle
        remaining_time = (self.attribution.spectacle.date
                          - self.date - timedelta(hours=13))
        # Au minimum, on attend 2 jours avant le tirage
        delay = min(remaining_time, timedelta(days=2))
        # Le vendeur a aussi 1h pour changer d'avis
        return self.date + delay + timedelta(hours=1)

    def __str__(self):
        return "%s -- %s" % (self.seller,
                             self.attribution.spectacle.title)

    class Meta:
        verbose_name = "Revente"

    def send_notif(self):
        """
        Envoie une notification pour indiquer la mise en vente d'une place sur
        BdA-Revente à tous les intéressés.
        """
        inscrits = self.attribution.spectacle.subscribed.select_related('user')
        datatuple = [(
            'bda-revente',
            {
                'member': participant.user,
                'show': self.attribution.spectacle,
                'revente': self,
                'site': Site.objects.get_current()
            },
            settings.MAIL_DATA['revente']['FROM'],
            [participant.user.email])
            for participant in inscrits
        ]
        send_mass_custom_mail(datatuple)
        self.notif_sent = True
        self.save()

    def mail_shotgun(self):
        """
        Envoie un mail à toutes les personnes intéréssées par le spectacle pour
        leur indiquer qu'il est désormais disponible au shotgun.
        """
        inscrits = self.attribution.spectacle.subscribed.select_related('user')
        datatuple = [(
            'bda-shotgun',
            {

bda/forms.py
# -*- coding: utf-8 -*-

from django import forms
from django.forms.models import BaseInlineFormSet
from django.utils import timezone

from bda.models import Attribution, Spectacle


class InscriptionInlineFormSet(BaseInlineFormSet):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # self.instance is a Participant object
        tirage = self.instance.tirage

        # set once for all "spectacle" field choices
        # - restrict choices to the spectacles of this tirage
        # - force_choices avoid many db requests
        spectacles = tirage.spectacle_set.select_related('location')
        choices = [(sp.pk, str(sp)) for sp in spectacles]
        self.force_choices('spectacle', choices)

    def force_choices(self, name, choices):
        """Set choices of a field.

        As ModelChoiceIterator (default use to get choices of a
        ModelChoiceField), it appends an empty selection if requested.

        """
        for form in self.forms:
            field = form.fields[name]
            if field.empty_label is not None:
                field.choices = [('', field.empty_label)] + choices
            else:
                field.choices = choices


class TokenForm(forms.Form):
    token = forms.CharField(widget=forms.widgets.Textarea())


class AttributionModelMultipleChoiceField(forms.ModelMultipleChoiceField):
    def label_from_instance(self, obj):
        return "%s" % str(obj.spectacle)


class ResellForm(forms.Form):
    attributions = AttributionModelMultipleChoiceField(
                         label='',
                         queryset=Attribution.objects.none(),
                         widget=forms.CheckboxSelectMultiple,
                         required=False)

    def __init__(self, participant, *args, **kwargs):
        super(ResellForm, self).__init__(*args, **kwargs)
        self.fields['attributions'].queryset = (
            participant.attribution_set
            .filter(spectacle__date__gte=timezone.now())
            .exclude(revente__seller=participant)
            .select_related('spectacle', 'spectacle__location',
                            'participant__user')
        )


class AnnulForm(forms.Form):
    attributions = AttributionModelMultipleChoiceField(
                         label='',
                         queryset=Attribution.objects.none(),
                         widget=forms.CheckboxSelectMultiple,
                         required=False)

    def __init__(self, participant, *args, **kwargs):
        super(AnnulForm, self).__init__(*args, **kwargs)
        self.fields['attributions'].queryset = (
            participant.attribution_set
            .filter(spectacle__date__gte=timezone.now(),
                    revente__isnull=False,
                    revente__notif_sent=False,
                    revente__soldTo__isnull=True)
            .select_related('spectacle', 'spectacle__location',
                            'participant__user')
        )


class InscriptionReventeForm(forms.Form):
    spectacles = forms.ModelMultipleChoiceField(
                    queryset=Spectacle.objects.none(),
                    widget=forms.CheckboxSelectMultiple,
                    required=False)

    def __init__(self, tirage, *args, **kwargs):
        super(InscriptionReventeForm, self).__init__(*args, **kwargs)
        self.fields['spectacles'].queryset = (
            tirage.spectacle_set
            .select_related('location')
            .filter(date__gte=timezone.now())
        )


class SoldForm(forms.Form):
    attributions = AttributionModelMultipleChoiceField(
                        label='',
                        queryset=Attribution.objects.none(),
                        widget=forms.CheckboxSelectMultiple)

    def __init__(self, participant, *args, **kwargs):
        super(SoldForm, self).__init__(*args, **kwargs)
        self.fields['attributions'].queryset = (
            participant.attribution_set
            .filter(revente__isnull=False,
                    revente__soldTo__isnull=False)
            .exclude(revente__soldTo=participant)
            .select_related('spectacle', 'spectacle__location',
                            'participant__user')
        )

bda/templates/bda-attrib.html
{% extends "base_title.html" %}
{% load staticfiles %}

{% block extra_head %}
	<link type="text/css" rel="stylesheet" href="{% static "css/bda.css" %}" />
{% endblock %}

{% block realcontent %}

<h2>Attributions</h2>

<br />
<p class="success">Pour raison de sécurité, le lancement du tirage
	a été désactivé. Vous pouvez le réactiver dans
	l'<a href="{% url "admin:index" %}">interface admin</a></p>

<h3 class="horizontal-title">Token :</h3>
<pre>{{ token }}</pre> 
<h3 class="horizontal-title">Placés : {{ total_slots }} ; Déçus : {{ total_losers }}</h3>
{% if user.profile.is_buro %}<h3 class="horizontal-title">Déficit total: {{ total_deficit }} €, Opéra: {{ opera_deficit }} €, Attribué: {{ total_sold }} €</h3>{% endif %}
<h3 class="horizontal-title">Temps de calcul : {{ duration|floatformat }}s</h3>

{% for show, members, losers in results %}
<div class="attribresult">
<h3 class="horizontal-title">{{ show.title }} - {{ show.date }} @ {{ show.location }}</h3>
<p>
<strong>{{ show.nrequests }} demandes pour {{ show.slots }} places</strong>
{{ show.price }}€ par place{% if user.profile.is_buro and show.nrequests < show.slots %}, {{ show.deficit }}€ de déficit{% endif %}
</p>
Places :
<ul>
{% for member, rank, origrank, double in members %}
    <li>{{ member.user.get_full_name }} <span class="details">(souhait {{ origrank }} &mdash; rang {{ rank }})</span></li>
{% endfor %}
</ul>
Déçus :
{% if not losers %}/{% else %}
<ul class="losers">
{% for member, rank, origrank, double in losers %}
{% if not forloop.first %} ; {% endif %}
    <li>{{ member.user.get_full_name }} <span class="details">(souhait {{ origrank }} &mdash; rang {{ rank }})</span></li>
{% endfor %}
</ul> 
{% endif %}
</div>
{% endfor %}
{% block extracontent %}
{% endblock %}
{% endblock %}

bda/templates/bda-emails.html
{% extends "base_title.html" %}

{% block realcontent %}
    <h2>{{ spectacle }}</h2>
    <textarea style="width: 100%; height: 100px; margin-top: 10px;">
{% for attrib in spectacle.attribues.all %}{{ attrib.participant.user.email }}, {% endfor %}</textarea>
{% endblock %}

bda/templates/bda-interested.html
{% extends "base_title.html" %}
{% load staticfiles %}

{% block realcontent %}
<h2>Inscription à une revente</h2>
<p class="success"> Votre inscription a bien été enregistrée !</p>
<p>Le tirage au sort pour cette revente ({{spectacle}}) sera effectué le {{date}}.

{% endblock %}

bda/templates/bda-no-revente.html
{% extends "base_title.html" %}

{% block realcontent %}
    <h2>BdA-Revente</h2>
    <p>Il n'y a plus de places en revente pour ce spectacle, désolé !</p>
{% endblock %}

bda/templates/bda-notpaid.html
{% extends "base_title.html" %}

{% block realcontent %}
    <h2><strong>Nope</strong></h2>
    <p>Avant de revendre des places, il faut aller les payer !</p>
{% endblock %}

bda/templates/bda-shotgun.html
{% extends "base_title.html" %}

{% block realcontent %}
  <h2>Places disponibles immédiatement</h2>
  {% if shotgun %}
    <ul class="list-unstyled">
    {% for spectacle in shotgun %}
    <li><a href="{% url "bda-buy-revente" spectacle.id %}">{{spectacle}}</a></li>
    {% endfor %}
  {% else %}
    <p> Pas de places disponibles immédiatement, désolé !</p>
  {% endif %}

{% endblock %}

bda/templates/bda-success.html
{% extends "base_title.html" %}
{% load staticfiles %}

{% block realcontent %}

<h2>Revente de place</h2>
<p class="success">Un mail a bien été envoyé à {{seller.get_full_name}} ({{seller.email}}), pour racheter une place pour {{spectacle.title}} !</p>
{% endblock %}

bda/templates/bda-token.html
{% extends "base_title.html" %}

{% block realcontent %}
<h2>Tirage au sort du BdA</h2>
<form action="" method="post" id="tokenform">
    {% csrf_token %}
    <strong>La graine :</strong>
    <div>
    {{ form.token }}
    </div>
    <input type="submit" onsubmit="return confirm('Voulez vous lancer le Tirage maintenant ?\n\nCECI REMETTRA À ZÉRO TOUTES LES DONNÉES si le tirage a déjà été lancé.')" value="Go" />
</form>
{% endblock %}

bda/templates/bda-unpaid.html
{% extends "base_title.html" %}

{% block realcontent %}
    <h2>Impayés</h2>
    <textarea style="width: 100%; height: 100px; margin-top: 10px;">
{% for participant in unpaid %}{{ participant.user.email }}, {% endfor %}</textarea>
    <h3>Total&nbsp: {{ unpaid|length }}</h3>
{% endblock %}

bda/templates/bda-wrongtime.html
{% extends "base_title.html" %}

{% block realcontent %}
<h2>Nope</h2>
    {% if revente.shotgun %}
    <p>Le tirage au sort de cette revente a déjà été effectué !</p>

    <p>Si personne n'était intéressé, elle est maintenant disponible 
    <a href="{% url "bda-buy-revente" revente.attribution.spectacle.id %}">ici</a>.</p>
    {% else %}
    <p> Il n'est pas encore possible de s'inscrire à cette revente, réessaie dans quelque temps !</p>
    {% endif %}
{% endblock %}

bda/templates/descriptions.html
{% load staticfiles %}

<!doctype html>
<html>
    <head>
	 	  <base target="_parent"/>
        <style>
        @font-face {
            font-family: josefinsans;
            src: url({% static "fonts/josefinsans.ttf" %});
        }

        *::-moz-selection {
            background: #B0B0B0;
        }

        *::selection {
            background: #B0B0B0;
        }

        .descTable{
            width: 100%;
            margin: 0 auto 1em;
            border-bottom: 2px solid;
            border-collapse: collapse;
            border-spacing: 0;
            font-size: 14px;
            line-height: 2;
            max-width: 100%;
            background-color: transparent;
            font-family: 'josefinsans', 'Arial';
            font-weight: 700;
            color: #5a5a5a;
        }

		  img{
		  	   max-width: 100%;
		  }
        </style>
        <meta charset="utf8" />
    </head>
	 <script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
    <body>
        {% for show in shows %}
        <table class="descTable">
            <thead>
                <tr>
                    <th colspan="2"><p style="text-align:center;font-size:22px;">{{ show.title }}</p></th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td><p style="text-align: left;">{{ show.location }}</p></td><td class="column-2"><p style="text-align: right;">{{ show.category }}</p></td>
                </tr>
                <tr>
                    <td><p style="text-align: left;">{{ show.date|date:"l j F Y - H\hi" }}</p></td><td class="column-2"><p style="text-align: right;">{{ show.slots }} place{{ show.slots|pluralize}} {% if show.slots_description != "" %}({{ show.slots_description }}){% endif %} - {{ show.price }} euro{{ show.price|pluralize}}</p></td>
                </tr>
					 {% if show.vips %}
				 	 <tr>
					 	  <td colspan="2"><p style="text-align: justify;">{{ show.vips }}</p></td>
					 </tr>
					 {% endif %}
					 <tr>
                    <td colspan="2">
                    <p style="text-align: justify;">{{ show.description }}</p>
                    {% for quote in show.quote_set.all %}
                    <p style="text-align:center; font-style: italic;">«{{ quote.text }}»{% if quote.author %} - {{ quote.author }}{% endif %}</p>
                    {% endfor %}
                    </td>
                </tr>
                {% if show.image %}
                <tr>
                    <td colspan="2"><p style="text-align:center;"><a href="{{ show.ext_link }}"><img class="imgDesc" style="display: inline;" src="{{ MEDIA_URL }}{{ show.image }}" alt="{{ show.title }}"></a></p></td>
                </tr>
                {% endif %}
            </tbody>
        </table>
        {% endfor %}
		  <script>
				// Correction de la taille des images
				
				/*$(document).ready(function() {
					$(".descTable").each(function() {
						$(this).width($("body").width());
					});
					
					$(".imgDesc").on("load", function() {
				
						// Dimensions
						origHeight = 500; // Hauteur souhaitée

						w = $(this).width();
						h = $(this).height();
						r = w/h; // Ratio de l'image
						maxWidth = $("body").width();

						if (r * origHeight > maxWidth)
						{
							$(this).width(maxWidth);
							$(this).height(maxWidth/r);
						}
						else
						{
							$(this).width(r * origHeight);
							$(this).height(origHeight);
						}
					});
				});*/


		  </script>
    </body>
</html>

bda/templates/revente-confirm.html
{% extends "base_title.html" %}
{% load staticfiles %}


{%block realcontent %}
<h2>Rachat d'une place</h2>
<form action="" method="post">
{% csrf_token %}
<pre>
Bonjour !

Je souhaiterais racheter ta place pour {{spectacle.title}} le {{spectacle.date}} ({{spectacle.location}}) à {{spectacle.price}}€. 
Contacte-moi si tu es toujours intéressé-e !

{{user.get_full_name}} ({{user.email}})
</pre>
<input type="submit" class="btn btn-primary pull-right" value="Envoyer">
</form>
<p class="bda-prix">Note : ce mail sera envoyé à une personne au hasard revendant sa place.</p>
{%endblock%}

bda/templates/spectacle_list.html
{% extends "base_title.html" %}
{% load staticfiles %}

{% block extra_head %}
    <link type="text/css" rel="stylesheet" href="{% static "css/bda.css" %}" />
{% endblock %}

{% block realcontent %}
    <h2><strong>{{tirage_name}}</strong></h2>
    <h3>Liste des spectacles</h3>


    <table class="table table-striped table-hover etat-bda">
        <thead>
        <tr>
            <th data-sort="string">Titre</th>
            <th data-sort="int">Date</th>
            <th data-sort="string">Lieu</th>
            <th data-sort="float">Prix</th>
        </tr> 
        </thead>
        <tbody>
        {% for spectacle in object_list %}
	    <tr class="clickable-row {% if spectacle.is_past %}spectacle-passe{% endif %}" data-href="{% url 'bda-spectacle' tirage_id spectacle.id %}"> 
                <td><a href="{% url 'bda-spectacle' tirage_id spectacle.id %}">{{ spectacle.title }} <span style="font-size:small;" class="glyphicon glyphicon-link" aria-hidden="true"></span></a></td>
                <td data-sort-value="{{ spectacle.timestamp }}"">{{ spectacle.date }}</td>
                <td data-sort-value="{{ spectacle.location }}">{{ spectacle.location }}</td>
                <td data-sort-value="{{ spectacle.price |stringformat:".3f" }}">
                                {{ spectacle.price |floatformat  }}€
            </td>
        </tr>
                    {% endfor %}
        </tbody>
        </table>
	<script type="text/javascript"
	        src="{% static "js/joequery-Stupid-Table-Plugin/stupidtable.js" %}">
        </script>
    <script type="text/javascript">
        $(function(){
        $("table.etat-bda").stupidtable();
        });
    </script>
    <script>
    jQuery(document).ready(function($) {
        $(".clickable-row").click(function() {
        window.document.location = $(this).data("href");
        });
    });
    </script>

    <h3> Exports </h3>
    <ul>
        <li><a href="{% url 'bda-unpaid' tirage_id  %}">Mailing list impayés</a>
        <li><a href="{% url 'bda-descriptions' tirage_id %}">Lien vers les descriptions des spectacles, à utiliser dans une page wordpress</a>
    </ul>
{% endblock %}

bda/templates/tirage-failed.html
{% extends "base_title.html" %}

{% block realcontent %}
<h2>Raté, le tirage ne peut pas être lancé&#8239;!</h2>

<p>Soit les inscriptions ne sont en pas encore fermées, soit le lancement du
tirage est désactivé. Si vous savez ce que vous faites, vous pouvez autoriser
le lancement du tirage dans
l'<a href="{% url "admin:index" %}">interface admin</a>.</p>
{% endblock %}